export enum PopupsActionType {
  FETCH_ALL_POPUPS = 'FETCH_ALL_POPUPS',
  FETCH_ALL_POPUPS_SUCCESS = 'FETCH_ALL_POPUPS_SUCCESS',
  FETCH_ALL_POPUPS_ERROR = 'FETCH_ALL_POPUPS_ERROR',

  FETCH_POPUP_BY_ID = 'FETCH_POPUP_BY_ID',
  FETCH_POPUP_BY_ID_SUCCESS = 'FETCH_POPUP_BY_ID_SUCCESS',
  FETCH_POPUP_BY_ID_ERROR = 'FETCH_POPUP_BY_ID_ERROR',

  CREATE_POPUP = 'CREATE_POPUP',
  CREATE_POPUP_SUCCESS = 'CREATE_POPUP_SUCCESS',
  CREATE_POPUP_ERROR = 'CREATE_POPUP_ERROR',

  UPDATE_POPUP_BY_ID = 'UPDATE_POPUP_BY_ID',
  UPDATE_POPUP_BY_ID_SUCCESS = 'UPDATE_POPUP_BY_ID_SUCCESS',
  UPDATE_POPUP_BY_ID_ERROR = 'UPDATE_POPUP_BY_ID_ERROR',

  DELETE_POPUP_BY_ID = 'DELETE_POPUP_BY_ID',
  DELETE_POPUP_BY_ID_SUCCESS = 'DELETE_POPUP_BY_ID_SUCCESS',
  DELETE_POPUP_BY_ID_ERROR = 'DELETE_POPUP_BY_ID_ERROR',
}
