export enum PopupsActionType {
  FETCH_ALL_POPUPS = 'FETCH_ALL_POPUPS',
  FETCH_ALL_POPUPS_SUCCESS = 'FETCH_ALL_POPUPS_SUCCESS',
  FETCH_ALL_POPUPS_ERROR = 'FETCH_ALL_POPUPS_ERROR',

  CREATE_POPUP = 'CREATE_POPUP',
  CREATE_POPUP_SUCCESS = 'CREATE_POPUP_SUCCESS',
  CREATE_POPUP_ERROR = 'CREATE_POPUP_ERROR',
}
