export enum UpdateUserActionType {
  UPDATE_USER_ADMIN_STATUS = 'UPDATE_USER_ADMIN_STATUS',
  UPDATE_USER_ADMIN_STATUS_SUCCESS = 'UPDATE_USER_ADMIN_STATUS_SUCCESS',
  UPDATE_USER_ADMIN_STATUS_ERROR = 'UPDATE_USER_ADMIN_STATUS_ERROR',
}
