export enum UserSearchActionType {
  FETCH_USERS = 'FETCH_USERS',
  FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR = 'FETCH_USERS_ERROR',

  FETCH_USER_BY_STID = 'FETCH_USER_BY_STID',
  FETCH_USER_BY_STID_SUCCESS = 'FETCH_USER_BY_STID_SUCCESS',
  FETCH_USER_BY_STID_ERROR = 'FETCH_USER_BY_STID_ERROR',

  SEARCH_USERS = 'SEARCH_USERS',
  SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS',
  SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR',
}
