export enum CreateEventDetailActionType {
  CREATE_EVENT_DETAIL = 'CREATE_EVENT_DETAIL',
  CREATE_EVENT_DETAIL_SUCCESS = 'CREATE_EVENT_DETAIL_SUCCESS',
  CREATE_EVENT_DETAIL_ERROR = 'CREATE_EVENT_DETAIL_ERROR',

  GET_S3_URL = 'GET_S3_URL',
  GET_S3_URL_SUCCESS = 'GET_S3_URL_SUCCESS',
  GET_S3_URL_ERROR = 'GET_S3_URL_ERROR',
}
