export enum EventAcionType {
  FETCH_EVENTS = 'FETCH_EVENTS',
  FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR',

  CREATE_EVENT = 'CREATE_EVENT',
  CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS',
  CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR',

  UPDATE_EVENT = 'UPDATE_EVENT',
  UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS',
  UPDATE_EVENT_ERROR = 'UPDATE_EVENT_ERROR',

  UPDATE_EVENT_DETAIL = 'UPDATE_EVENT_DETAIL',
  UPDATE_EVENT_DETAIL_SUCCESS = 'UPDATE_EVENT_DETAIL_SUCCESS',
  UPDATE_EVENT_DETAIL_ERROR = 'UPDATE_EVENT_DETAIL_ERROR',

  DELETE_EVENT = 'DELETE_EVENT',
  DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR',

  CREATE_EVENT_DETAIL = 'CREATE_EVENT_DETAIL',
  CREATE_EVENT_DETAIL_SUCCESS = 'CREATE_EVENT_DETAIL_SUCCESS',
  CREATE_EVENT_DETAIL_ERROR = 'CREATE_EVENT_DETAIL_ERROR',

  FETCH_EVENT_DETAILS_BY_EVENT_ID = 'FETCH_EVENT_DETAILS_BY_EVENT_ID',
  FETCH_EVENT_DETAILS_BY_EVENT_ID_SUCCESS = 'FETCH_EVENT_DETAILS_BY_EVENT_ID_SUCCESS',
  FETCH_EVENT_DETAILS_BY_EVENT_ID_ERROR = 'FETCH_EVENT_DETAILS_BY_EVENT_ID_ERROR',

  FETCH_EVENT_DETAIL_BY_DETAIL_ID = 'FETCH_EVENT_DETAIL_BY_DETAIL_ID',
  FETCH_EVENT_DETAIL_BY_DETAIL_ID_SUCCESS = 'FETCH_EVENT_DETAIL_BY_DETAIL_ID_SUCCESS',
  FETCH_EVENT_DETAIL_BY_DETAIL_ID_ERROR = 'FETCH_EVENT_DETAIL_BY_DETAIL_ID_ERROR',

  DELETE_EVENT_DETAIL = 'DELETE_EVENT_DETAIL',
  DELETE_EVENT_DETAIL_SUCCESS = 'DELETE_EVENT_DETAIL_SUCCESS',
  DELETE_EVENT_DETAIL_ERROR = 'DELETE_EVENT_DETAIL_ERROR',
}
