export enum FetchEventsActionType {
  FETCH_EVENTS = 'FETCH_EVENTS',
  FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR',

  FETCH_EVENT_DETAIL = 'FETCH_EVENT_DETAIL',
  FETCH_EVENT_DETAIL_SUCCESS = 'FETCH_EVENT_DETAIL_SUCCESS',
  FETCH_EVENT_DETAIL_ERROR = 'FETCH_EVENT_DETAIL_ERROR',
}
